### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.testing#16]
This package is not yet compatible with Python 3.6, see https://travis-ci.org/zopefoundation/zopetoolkit/jobs/173487024#L875

**Comment by mgedmin** [comment]
Full test log:
```
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
Failure in test /home/travis/build/zopefoundation/zopetoolkit/eggs/zope.testing-4.5.0-py3.6.egg/zope/testing/module.txt
Failed doctest test for module.txt
  File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.testing-4.5.0-py3.6.egg/zope/testing/module.txt", line 0
----------------------------------------------------------------------
File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.testing-4.5.0-py3.6.egg/zope/testing/module.txt", line 80, in module.txt
Failed example:
    import fake
Expected:
    Traceback (most recent call last):
      ...
    ImportError: No module named fake
Got:
    Traceback (most recent call last):
      File "/opt/python/3.6-dev/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest module.txt[20]>", line 1, in <module>
        import fake
    ModuleNotFoundError: No module named fake
----------------------------------------------------------------------
File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.testing-4.5.0-py3.6.egg/zope/testing/module.txt", line 97, in module.txt
Failed example:
    import zope.testing.unlikelymodulename
Expected:
    Traceback (most recent call last):
      ...
    ImportError: No module named unlikelymodulename
Got:
    Traceback (most recent call last):
      File "/opt/python/3.6-dev/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest module.txt[28]>", line 1, in <module>
        import zope.testing.unlikelymodulename
    ModuleNotFoundError: No module named unlikelymodulename
  Ran 6 tests with 1 failures, 0 errors and 0 skipped in 0.162 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

Should be simple to fix with a doctest renormalizer.
